using System.ComponentModel;
using System.Diagnostics;
using System.IO;
using System.Text;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shell;
using Lokql.Engine;
using Microsoft.Win32;
using NotNullStrings;

namespace lokqlDx;

public partial class MainWindow : Window
{
    private readonly string[] _args;
    private readonly WpfConsole _console;
    private readonly Size _minWindowSize = new(600, 400);
    private readonly PreferencesManager _preferenceManager = new();
    private readonly WebViewRenderer _renderingSurface;
    private readonly WorkspaceManager _workspaceManager;

    private Copilot _copilot = new(string.Empty);
    private InteractiveTableExplorer _explorer;

    private Workspace currentWorkspace = new();
    private bool isBusy;


    public MainWindow(
        string[] args
    )
    {
        _args = args.ToArray();
        InitializeComponent();
        _console = new WpfConsole(OutputText);

        _workspaceManager = new WorkspaceManager();
        var settings = _workspaceManager.Settings;
        var loader = new StandardFormatAdaptor(settings, _console);
        var cp = CommandProcessorProvider.GetCommandProcessor();
        _renderingSurface = new WebViewRenderer(RenderingSurface, webview, dataGrid,
            DatagridOverflowWarning,
            settings);
        _explorer = new InteractiveTableExplorer(_console, loader, settings, cp, _renderingSurface);
    }

    private async Task RunQuery(string query)
    {
        if (query.IsBlank())
            return;
        if (isBusy)
            return;
        isBusy = true;
        Editor.SetBusy(true);
        //start capturing console output from the engine
        _console.PrepareForOutput();
        //run the supplied lines of kusto/commands
        //Note that we need the extra Task.Run here to ensure
        //that the UI thread is not blocked for reports generated by
        //the engine
        await Task.Run(async () => await _explorer.RunInput(query));

        Editor.SetSchema(_explorer.GetSchema());
        Editor.AddSettingsForIntellisense(_explorer.Settings);
        Editor.SetBusy(false);
        isBusy = false;
    }


    /// <summary>
    ///     Called when user presses SHIFT-ENTER in the query editor
    /// </summary>
    private async void OnQueryEditorRunTextBlock(object? sender, QueryEditorRunEventArgs eventArgs)
    {
        await RunQuery(eventArgs.Query);
    }


    private async Task UpdateUIFromWorkspace()
    {
        Editor.SetText(currentWorkspace.Text);
        var settings = _workspaceManager.Settings;
        var loader = new StandardFormatAdaptor(settings, _console);
        _explorer = new InteractiveTableExplorer(_console, loader, settings,
            CommandProcessorProvider.GetCommandProcessor(), _renderingSurface);
        Title = $"LokqlDX - {_workspaceManager.Path.OrWhenBlank("new workspace")}";
        dataGrid.ItemsSource = null;
        await Navigate("https://github.com/NeilMacMullen/kusto-loco/wiki/LokqlDX");
    }

    private void RebuildRecentFilesList()
    {
        string GetHeaderForPath(string s)
        {
            return $"{Path.GetFileName(s)} ({Path.GetDirectoryName(s)})";
        }

        RecentlyUsed.Items.Clear();
        foreach (var path in _preferenceManager.GetMruItems().Take(10))
        {
            var menuitem = new MenuItem
            {
                Header = GetHeaderForPath(path),
                DataContext = path
            };
            menuitem.Click += RecentlyUsedFileClicked;
            RecentlyUsed.Items.Add(menuitem);
        }
    }

    private void UpdateMostRecentlyUsed(string path)
    {
        if (path.IsBlank())
            return;
        _preferenceManager.BringToTopOfMruList(path);

        JumpList.AddToRecentCategory(path);

        RebuildRecentFilesList();
    }

    private void UpdateDynamicUiFromPreferences()
    {
        var preferences = _preferenceManager.UIPreferences;
        Editor.SetFont(preferences.FontFamily);
        Editor.SetWordWrap(preferences.WordWrap);
        Editor.ShowLineNumbers(preferences.ShowLineNumbers);
        OutputText.FontFamily = new FontFamily(preferences.FontFamily);
        Editor.SetFontSize(preferences.FontSize);
        OutputText.FontSize = preferences.FontSize;
        dataGrid.FontSize = preferences.FontSize;
        UserChat.FontSize = preferences.FontSize;
        ChatHistory.FontSize = preferences.FontSize;
        if (preferences.EditorGridHeight > 10)
            EditorConsoleGrid.RowDefinitions[0].Height =
            new GridLength(preferences.EditorGridHeight  ,GridUnitType.Pixel);
        if (preferences.EditorGridWidth > 10)
            MainGrid.ColumnDefinitions[0].Width =
                new GridLength(preferences.EditorGridWidth, GridUnitType.Pixel);
    }

    private async void MainWindow_OnLoaded(object sender, RoutedEventArgs e)
    {
        _preferenceManager.RetrieveUiPreferencesFromDisk();
        Editor.AddInternalCommands(_explorer._commandProcessor.GetVerbs()
            .Select(v =>
                new IntellisenseEntry(v.Key, v.Value, string.Empty))
            .ToArray());
        RegistryOperations.AssociateFileType(true);
        PreferencesManager.EnsureDefaultFolderExists();
        UpdateDynamicUiFromPreferences();
        RebuildRecentFilesList();
        ResizeWindowAccordingToStoredPreferences();
        var pathToLoad = _args.Any()
            ? _args[0]
            : string.Empty;
        await LoadWorkspace(pathToLoad);
        await Navigate("https://github.com/NeilMacMullen/kusto-loco/wiki/LokqlDX");
    }


    private void ResizeWindowAccordingToStoredPreferences()
    {
        var ui = _preferenceManager.UIPreferences;
        if (Width > 100 && Height > 100 && Left > 0 && Top > 0)
        {
            Width = ui.WindowWidth < _minWindowSize.Width
                ? _minWindowSize.Width
                : ui.WindowWidth;
            Height = ui.WindowHeight < _minWindowSize.Height
                ? _minWindowSize.Height
                : ui.WindowHeight;
            Left = ui.WindowLeft;
            Top = ui.WindowTop;
        }
    }

    private async void RecentlyUsedFileClicked(object sender, RoutedEventArgs e)
    {
        if (sender is MenuItem { DataContext: string mruItem }) await LoadWorkspace(mruItem);
    }

    private void PersistUiPreferencesToDisk()
    {
        var ui = _preferenceManager.UIPreferences;
        ui.WindowLeft = Left;
        ui.WindowTop = Top;
        ui.WindowWidth = Width;
        ui.WindowHeight = Height;
        ui.EditorGridHeight = EditorConsoleGrid.RowDefinitions[0].Height.Value;
        ui.EditorGridWidth= MainGrid.ColumnDefinitions[0].Width.Value;
        _preferenceManager.SaveUiPrefs();
    }

    private void SaveWorkspace(string path)
    {
        UpdateCurrentWorkspaceFromUI();
        _workspaceManager.Save(path, currentWorkspace);
        _preferenceManager.BringToTopOfMruList(path);
    }

    /// <summary>
    ///     Allow the user to save any pending changes
    /// </summary>
    /// <returns>
    ///     true if the user wants to cancel the operation
    /// </returns>
    private async Task<bool> OfferSaveOfCurrentWorkspace()
    {
        if (CheckIfWorkspaceDirty())
        {
            var result = MessageBox.Show(
                "You have have unsaved changes. Do you want to save them?",
                "Warning", MessageBoxButton.YesNoCancel);
            if (result == MessageBoxResult.Cancel) return true;

            if (result == MessageBoxResult.Yes)
                await Save();
        }

        return false;
    }

    private async void MainWindow_OnClosing(object? sender, CancelEventArgs e)
    {
        if (await OfferSaveOfCurrentWorkspace())
        {
            e.Cancel = true;
            return;
        }


        //save the window size and position, font size etc regardless
        PersistUiPreferencesToDisk();
    }

    private async Task LoadWorkspace(string path)
    {
        if (await OfferSaveOfCurrentWorkspace()) return;

        //make sure we have the most recent global preferences
        var appPrefs = _preferenceManager.FetchApplicationPreferencesFromDisk();
        _workspaceManager.Load(path);
        currentWorkspace = _workspaceManager.Workspace;
        await RunQuery(appPrefs.StartupScript);
        await RunQuery(_workspaceManager.Workspace.StartupScript);
        UpdateMostRecentlyUsed(path);
        await UpdateUIFromWorkspace();
    }

    private async void OnOpenWorkSpace(object sender, RoutedEventArgs e)
    {
        var folder = _workspaceManager.ContainingFolder();
        var dialog = new OpenFileDialog
        {
            InitialDirectory = folder,
            Filter = $"Lokql Workspace ({WorkspaceManager.GlobPattern})|{WorkspaceManager.GlobPattern}",
            FileName = Path.GetFileName(_workspaceManager.Path)
        };

        if (dialog.ShowDialog() == true)
            await LoadWorkspace(dialog.FileName);
    }


    private async void OnSaveWorkspace(object sender, RoutedEventArgs e)
    {
        await Save();
    }

    private void UpdateCurrentWorkspaceFromUI()
    {
        currentWorkspace = currentWorkspace with { Text = Editor.GetText() };
    }

    private bool CheckIfWorkspaceDirty()
    {
        UpdateCurrentWorkspaceFromUI();
        return _workspaceManager.IsDirty(currentWorkspace);
    }

    private async Task Save()
    {
        if (!CheckIfWorkspaceDirty())
            return;
        if (_workspaceManager.Path.IsBlank())
        {
            await SaveAs();
            return;
        }

        SaveWorkspace(_workspaceManager.Path);
    }

    private async Task<bool> SaveAs()
    {
        var dialog = new SaveFileDialog
        {
            Filter = $"Lokql Workspace ({WorkspaceManager.GlobPattern})|{WorkspaceManager.GlobPattern}",
            FileName = Path.GetFileName(_workspaceManager.Path)
        };
        if (dialog.ShowDialog() == true)
        {
            SaveWorkspace(dialog.FileName);
            //make sure we update title bar
            await UpdateUIFromWorkspace();
            return true;
        }

        return false;
    }

    private async void SaveWorkspaceAsEvent(object sender, RoutedEventArgs e)
    {
        await SaveAs();
    }

    private async void NewWorkspace(object sender, RoutedEventArgs e)
    {
        //save current
        await Save();
        await LoadWorkspace(string.Empty);
    }

    private void IncreaseFontSize(object sender, RoutedEventArgs e)
    {
        _preferenceManager.UIPreferences.FontSize = Math.Min(40, _preferenceManager.UIPreferences.FontSize + 1);
        UpdateDynamicUiFromPreferences();
    }

    private void DecreaseFontSize(object sender, RoutedEventArgs e)
    {
        _preferenceManager.UIPreferences.FontSize = Math.Max(6, _preferenceManager.UIPreferences.FontSize - 1);
        UpdateDynamicUiFromPreferences();
    }


    protected override void OnKeyDown(KeyEventArgs e)
    {
        base.OnKeyDown(e);

        // here I suppose the window's menu is named "MainMenu"
        MainMenu.RaiseMenuItemClickOnKeyGesture(e);
    }

    private async Task Navigate(string url)
    {
        await _renderingSurface.NavigateToUrl(new Uri(url));
    }

    private async void NavigateToGettingStarted(object sender, RoutedEventArgs e)
    {
        await Navigate("https://github.com/NeilMacMullen/kusto-loco/wiki/LokqlDX");
    }

    private async void NavigateToProjectPage(object sender, RoutedEventArgs e)
    {
        await Navigate("https://github.com/NeilMacMullen/kusto-loco");
    }

    private async void NavigateToKqlIntroductionPage(object sender, RoutedEventArgs e)
    {
        await Navigate(
            "https://learn.microsoft.com/en-us/azure/data-explorer/kusto/query/tutorials/learn-common-operators");
    }

    private void EnableJumpList(object sender, RoutedEventArgs e)
    {
        RegistryOperations.AssociateFileType(false);
    }

    private async void SubmitToCopilot(object sender, RoutedEventArgs e)
    {
        SubmitButton.IsEnabled = false;
        if (!_copilot.Initialised)
        {
            _copilot = new Copilot(_explorer.Settings.GetOr("copilot", string.Empty));
            foreach (var table in _explorer.GetCurrentContext().Tables())
            {
                var sb = new StringBuilder();
                sb.AppendLine($"The table named '{table.Name}' has the following columns");
                var cols = table.ColumnNames.Zip(table.Type.Columns)
                    .Select(z => $"  {z.First} is of type {z.Second.Type.Name}")
                    .ToArray();
                foreach (var column in cols) sb.AppendLine(column);
                _copilot.AddSystemInstructions(sb.ToString());
            }
        }

        var userchat = UserChat.Text;
        UserChat.Text = string.Empty;
        const int maxResubmissions = 3;
        for (var i = 0; i < maxResubmissions; i++)
        {
            var response = await _copilot.Issue(userchat);


            var console = new WpfConsole(ChatHistory);

            //now try to extract kql...
            var lines = response.Split('\n');
            var kql = new StringBuilder();
            var getting = false;
            foreach (var line in lines)
            {
                if (line.StartsWith("```kql") || line.StartsWith("```kusto"))
                {
                    kql.Clear();
                    getting = true;
                    continue;
                }

                if (line.StartsWith("```"))
                {
                    getting = false;
                    continue;
                }

                if (getting)
                    kql.AppendLine(line.Trim());
            }

            _copilot.AddResponse(kql.ToString());
            console.PrepareForOutput();
            var options = new List<string> { Copilot.Roles.System, Copilot.Roles.User, Copilot.Roles.Kql };
            if (TerseMode.IsChecked != true)
                options.Add(Copilot.Roles.Assistant);
            _copilot.RenderResponses(console, options.ToArray());

            if (kql.ToString().IsBlank())
                break;
            await RunQuery(kql.ToString());
            var lastResult = _explorer.GetPreviousResult();

            if (lastResult.Error.IsBlank())
                break;
            userchat = $"That query gave an error: {lastResult.Error}";
        }


        SubmitButton.IsEnabled = true;
    }

    private void ResetCopilot(object sender, RoutedEventArgs e)
    {
        _copilot = new Copilot(string.Empty);
        ChatHistory.Document.Blocks.Clear();
    }

    private void OpenApplicationOptionsDialog(object sender, RoutedEventArgs e)
    {
        //make sure we have the latest preferences
        var appPreferences = _preferenceManager.FetchApplicationPreferencesFromDisk();
        var dialog = new ApplicationPreferencesWindow(appPreferences,
            _preferenceManager.UIPreferences)
        {
            Owner = this
        };
        //TODO - this is a bit of a hack based on the fact we've put the
        //font in this dialog
        var oldFont = _preferenceManager.UIPreferences.FontFamily;
        if (dialog.ShowDialog() == true)
        {
            _preferenceManager.Save(appPreferences);
           
            UpdateDynamicUiFromPreferences();
        }
        else _preferenceManager.UIPreferences.FontFamily = oldFont;
    }

    private async void OpenWorkspaceOptionsDialog(object sender, RoutedEventArgs e)
    {
        UpdateCurrentWorkspaceFromUI();
        var dialog = new WorkspacePreferencesWindow(currentWorkspace, _preferenceManager.UIPreferences)
        {
            Owner = this
        };
        if (dialog.ShowDialog() == true)
        {
            currentWorkspace = dialog._workspace;
            await Save();
        }
    }

    private void ToggleWordWrap(object sender, RoutedEventArgs e)
    {
        _preferenceManager.UIPreferences.WordWrap = !_preferenceManager.UIPreferences.WordWrap;
        UpdateDynamicUiFromPreferences();
    }

    private void ToggleLineNumbers(object sender, RoutedEventArgs e)
    {
        _preferenceManager.UIPreferences.ShowLineNumbers = !_preferenceManager.UIPreferences.ShowLineNumbers;
        UpdateDynamicUiFromPreferences();
    }

    private async void OnCopyImageToClipboard(object sender, RoutedEventArgs e)
    {
        try
        {
            var bytes = await WebViewExtensions.CaptureImage(webview.CoreWebView2);
            using var memoryStream = new MemoryStream(bytes);
            var bitmapImage = new BitmapImage();
            bitmapImage.BeginInit();
            bitmapImage.StreamSource = memoryStream;
            bitmapImage.CacheOption = BitmapCacheOption.OnLoad;
            bitmapImage.EndInit();
            bitmapImage.Freeze(); // Freeze the image to make it cross-thread accessible
            Clipboard.SetImage(bitmapImage);
            _explorer.Info("Chart copied to clipboard");
        }
        catch
        {
        }
    }

    private void onOpenInBrowser(object sender, RoutedEventArgs e)
    {
        var textOrUri = _renderingSurface.LastRendered;
        if (textOrUri.Html.IsNotBlank())
        {
            var fileName = Path.ChangeExtension(Path.GetTempFileName(), "html");
            File.WriteAllText(fileName, textOrUri.Html);

            Process.Start(new ProcessStartInfo { FileName = fileName, UseShellExecute = true });
        }

        if (textOrUri.Uri.IsNotBlank())
        {
            var fileName = textOrUri.Uri;
            Process.Start(new ProcessStartInfo { FileName = fileName, UseShellExecute = true });
        }
    }

    private async void NavigateToDiscussionForum(object sender, RoutedEventArgs e)
    {
        await Navigate(@"https://github.com/NeilMacMullen/kusto-loco/discussions/categories/q-a");
    }
}
