//
// Licensed under the MIT License.

using System.Collections.Generic;

namespace KustoLoco.Geo;

/// <summary>
/// ISO 3166-1 alpha-2 code → English country name, matching ADX's <c>geo_info_from_ip_address(...).country</c> shape
/// (real ADX returns the country NAME, not the code). The names are exactly .NET's <see cref="System.Globalization.RegionInfo.EnglishName"/>
/// (generated from it once), but embedded as a fixed table so the mapping is available under
/// <c>InvariantGlobalization</c> — where <c>RegionInfo</c> throws and would otherwise silently degrade the country to
/// its raw code. Server workloads that host a KQL engine commonly run invariant (smaller, faster, deterministic), so
/// the table, not <c>RegionInfo</c>, is what makes the country name portable across globalization modes. An unknown
/// code (not in this table) falls back to the raw code, exactly as ADX passes through an unmapped value.
/// </summary>
internal static class CountryNames
{
    private static readonly Dictionary<string, string> Map = new(244, System.StringComparer.OrdinalIgnoreCase)
    {
        ["AD"]="Andorra",
        ["AE"]="United Arab Emirates",
        ["AF"]="Afghanistan",
        ["AG"]="Antigua & Barbuda",
        ["AI"]="Anguilla",
        ["AL"]="Albania",
        ["AM"]="Armenia",
        ["AO"]="Angola",
        ["AR"]="Argentina",
        ["AS"]="American Samoa",
        ["AT"]="Austria",
        ["AU"]="Australia",
        ["AW"]="Aruba",
        ["AX"]="Åland Islands",
        ["AZ"]="Azerbaijan",
        ["BA"]="Bosnia & Herzegovina",
        ["BB"]="Barbados",
        ["BD"]="Bangladesh",
        ["BE"]="Belgium",
        ["BF"]="Burkina Faso",
        ["BG"]="Bulgaria",
        ["BH"]="Bahrain",
        ["BI"]="Burundi",
        ["BJ"]="Benin",
        ["BL"]="St. Barthélemy",
        ["BM"]="Bermuda",
        ["BN"]="Brunei",
        ["BO"]="Bolivia",
        ["BQ"]="Bonaire, Sint Eustatius and Saba",
        ["BR"]="Brazil",
        ["BS"]="Bahamas",
        ["BT"]="Bhutan",
        ["BW"]="Botswana",
        ["BY"]="Belarus",
        ["BZ"]="Belize",
        ["CA"]="Canada",
        ["CC"]="Cocos (Keeling) Islands",
        ["CD"]="Congo (DRC)",
        ["CF"]="Central African Republic",
        ["CG"]="Congo",
        ["CH"]="Switzerland",
        ["CI"]="Côte d’Ivoire",
        ["CK"]="Cook Islands",
        ["CL"]="Chile",
        ["CM"]="Cameroon",
        ["CN"]="China",
        ["CO"]="Colombia",
        ["CR"]="Costa Rica",
        ["CU"]="Cuba",
        ["CV"]="Cabo Verde",
        ["CW"]="Curaçao",
        ["CX"]="Christmas Island",
        ["CY"]="Cyprus",
        ["CZ"]="Czechia",
        ["DE"]="Germany",
        ["DJ"]="Djibouti",
        ["DK"]="Denmark",
        ["DM"]="Dominica",
        ["DO"]="Dominican Republic",
        ["DZ"]="Algeria",
        ["EC"]="Ecuador",
        ["EE"]="Estonia",
        ["EG"]="Egypt",
        ["ER"]="Eritrea",
        ["ES"]="Spain",
        ["ET"]="Ethiopia",
        ["FI"]="Finland",
        ["FJ"]="Fiji",
        ["FK"]="Falkland Islands",
        ["FM"]="Micronesia",
        ["FO"]="Faroe Islands",
        ["FR"]="France",
        ["GA"]="Gabon",
        ["GB"]="United Kingdom",
        ["GD"]="Grenada",
        ["GE"]="Georgia",
        ["GF"]="French Guiana",
        ["GG"]="Guernsey",
        ["GH"]="Ghana",
        ["GI"]="Gibraltar",
        ["GL"]="Greenland",
        ["GM"]="Gambia",
        ["GN"]="Guinea",
        ["GP"]="Guadeloupe",
        ["GQ"]="Equatorial Guinea",
        ["GR"]="Greece",
        ["GT"]="Guatemala",
        ["GU"]="Guam",
        ["GW"]="Guinea-Bissau",
        ["GY"]="Guyana",
        ["HK"]="Hong Kong SAR",
        ["HN"]="Honduras",
        ["HR"]="Croatia",
        ["HT"]="Haiti",
        ["HU"]="Hungary",
        ["ID"]="Indonesia",
        ["IE"]="Ireland",
        ["IL"]="Israel",
        ["IM"]="Isle of Man",
        ["IN"]="India",
        ["IO"]="British Indian Ocean Territory",
        ["IQ"]="Iraq",
        ["IR"]="Iran",
        ["IS"]="Iceland",
        ["IT"]="Italy",
        ["JE"]="Jersey",
        ["JM"]="Jamaica",
        ["JO"]="Jordan",
        ["JP"]="Japan",
        ["KE"]="Kenya",
        ["KG"]="Kyrgyzstan",
        ["KH"]="Cambodia",
        ["KI"]="Kiribati",
        ["KM"]="Comoros",
        ["KN"]="St. Kitts & Nevis",
        ["KP"]="North Korea",
        ["KR"]="Korea",
        ["KW"]="Kuwait",
        ["KY"]="Cayman Islands",
        ["KZ"]="Kazakhstan",
        ["LA"]="Laos",
        ["LB"]="Lebanon",
        ["LC"]="St. Lucia",
        ["LI"]="Liechtenstein",
        ["LK"]="Sri Lanka",
        ["LR"]="Liberia",
        ["LS"]="Lesotho",
        ["LT"]="Lithuania",
        ["LU"]="Luxembourg",
        ["LV"]="Latvia",
        ["LY"]="Libya",
        ["MA"]="Morocco",
        ["MC"]="Monaco",
        ["MD"]="Moldova",
        ["ME"]="Montenegro",
        ["MF"]="St. Martin",
        ["MG"]="Madagascar",
        ["MH"]="Marshall Islands",
        ["MK"]="North Macedonia",
        ["ML"]="Mali",
        ["MM"]="Myanmar",
        ["MN"]="Mongolia",
        ["MO"]="Macao SAR",
        ["MP"]="Northern Mariana Islands",
        ["MQ"]="Martinique",
        ["MR"]="Mauritania",
        ["MS"]="Montserrat",
        ["MT"]="Malta",
        ["MU"]="Mauritius",
        ["MV"]="Maldives",
        ["MW"]="Malawi",
        ["MX"]="Mexico",
        ["MY"]="Malaysia",
        ["MZ"]="Mozambique",
        ["NA"]="Namibia",
        ["NC"]="New Caledonia",
        ["NE"]="Niger",
        ["NF"]="Norfolk Island",
        ["NG"]="Nigeria",
        ["NI"]="Nicaragua",
        ["NL"]="Netherlands",
        ["NO"]="Norway",
        ["NP"]="Nepal",
        ["NR"]="Nauru",
        ["NU"]="Niue",
        ["NZ"]="New Zealand",
        ["OM"]="Oman",
        ["PA"]="Panama",
        ["PE"]="Peru",
        ["PF"]="French Polynesia",
        ["PG"]="Papua New Guinea",
        ["PH"]="Philippines",
        ["PK"]="Pakistan",
        ["PL"]="Poland",
        ["PM"]="St. Pierre & Miquelon",
        ["PN"]="Pitcairn Islands",
        ["PR"]="Puerto Rico",
        ["PS"]="Palestinian Authority",
        ["PT"]="Portugal",
        ["PW"]="Palau",
        ["PY"]="Paraguay",
        ["QA"]="Qatar",
        ["RE"]="Réunion",
        ["RO"]="Romania",
        ["RS"]="Serbia",
        ["RU"]="Russia",
        ["RW"]="Rwanda",
        ["SA"]="Saudi Arabia",
        ["SB"]="Solomon Islands",
        ["SC"]="Seychelles",
        ["SD"]="Sudan",
        ["SE"]="Sweden",
        ["SG"]="Singapore",
        ["SH"]="St Helena, Ascension, Tristan da Cunha",
        ["SI"]="Slovenia",
        ["SJ"]="Svalbard & Jan Mayen",
        ["SK"]="Slovakia",
        ["SL"]="Sierra Leone",
        ["SM"]="San Marino",
        ["SN"]="Senegal",
        ["SO"]="Somalia",
        ["SR"]="Suriname",
        ["SS"]="South Sudan",
        ["ST"]="São Tomé & Príncipe",
        ["SV"]="El Salvador",
        ["SX"]="Sint Maarten",
        ["SY"]="Syria",
        ["SZ"]="Eswatini",
        ["TC"]="Turks & Caicos Islands",
        ["TD"]="Chad",
        ["TG"]="Togo",
        ["TH"]="Thailand",
        ["TJ"]="Tajikistan",
        ["TK"]="Tokelau",
        ["TL"]="Timor-Leste",
        ["TM"]="Turkmenistan",
        ["TN"]="Tunisia",
        ["TO"]="Tonga",
        ["TR"]="Türkiye",
        ["TT"]="Trinidad & Tobago",
        ["TV"]="Tuvalu",
        ["TW"]="Taiwan",
        ["TZ"]="Tanzania",
        ["UA"]="Ukraine",
        ["UG"]="Uganda",
        ["UM"]="U.S. Outlying Islands",
        ["US"]="United States",
        ["UY"]="Uruguay",
        ["UZ"]="Uzbekistan",
        ["VA"]="Vatican City",
        ["VC"]="St. Vincent & Grenadines",
        ["VE"]="Venezuela",
        ["VG"]="British Virgin Islands",
        ["VI"]="U.S. Virgin Islands",
        ["VN"]="Vietnam",
        ["VU"]="Vanuatu",
        ["WF"]="Wallis & Futuna",
        ["WS"]="Samoa",
        ["XK"]="Kosovo",
        ["YE"]="Yemen",
        ["YT"]="Mayotte",
        ["ZA"]="South Africa",
        ["ZM"]="Zambia",
        ["ZW"]="Zimbabwe",
    };

    /// <summary>English country name for an ISO alpha-2 code, or the raw code when unmapped/empty (ADX pass-through).</summary>
    public static string? EnglishName(string? code)
    {
        if (string.IsNullOrEmpty(code))
            return null;
        return Map.TryGetValue(code, out var name) ? name : code;
    }
}
