using System;
using KustoLoco.Core.DataSource.Columns;

namespace KustoLoco.Core.Evaluation.BuiltIns.Impl;

/*
  This file is autogenerated
*/

public static class IndexFinder
{
{{ for line in model 
   t=line.Type 
   tName = (t | string.capitalize)
}}

    public static int FindIndexOf{{tName}}(BaseColumn column, bool max)
    {
    
        var valueIndex = 0;
        var valueSoFar = max ? {{t}}.MinValue : {{t}}.MaxValue;
        var valuesColumn = (TypedBaseColumn<{{t}}?>) column;
        for (var i = 0; i < valuesColumn.RowCount; i++)
        {
            if (valuesColumn[i] is not { } n) continue;
            if ( max && n <= valueSoFar) continue;
            if (!max && n >= valueSoFar) continue;
            valueSoFar = n;
            valueIndex = i;
        }

        return valueIndex;
    }
{{end}}
}